spring.application.name=paymentgateway
server.port=5003
spring.datasource.url=jdbc:postgresql://43.204.7.55:5432/appdb?currentSchema=public
spring.datasource.username= ytadbdmin
spring.datasource.password= yajentio2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.log-request-details=true
logging.level.org.springframework.web=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kishoresekar2754@gmail.com
spring.mail.password=xgzz hway tgqj bzbp
jwt.secret=Cj6LHKrbq5Stgbk6VXtqoQLi2WSA4RcZenIeOwv1KII=
jwt.expiration=3600000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
razorpay.api.key=rzp_test_S05XiQKHjYK9gd
razorpay.api.secret=z9lxa73UGz8GBDcSySOyZ35S
razorpay.webhook.secret=ytaportal_webhook_secret_123
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.cloud.compatibility-verifier.enabled=false














